var cards =  [
    {
        id: 1,
        nome: "Half Orc",
        life: 40,
        attack: 20,
        defense: 15,
        price: 20,
        url:"https://p.kindpng.com/picc/s/487-4870713_dungeons-and-dragons-half-orc-barbarian-hd-png.png",
    },
    {
        id: 2,
        nome: "Archer",
        life: 25,
        attack: 15,
        defense: 5,
        price: 13,
        url:"https://p.kindpng.com/picc/s/654-6547403_dungeons-and-dragons-ranger-hd-png-download.png",
    },
    {
        id: 3,
        nome: "Mage",
        life: 10,
        attack: 30,
        defense: 1,
        price: 12,
        url:"https://www.kindpng.com/picc/m/206-2060731_pathfinder-roleplaying-game-dungeons-dragons-wizard-pathfinder-wizard.png",
    },
    {
        id: 4,
        nome: "Sacer",
        life: 30,
        attack: 5,
        defense: 25,
        price: 9,
        url:"https://p.kindpng.com/picc/s/251-2514230_druid-action-pose1-druid-dungeons-and-dragons-women.png",
    },
    {
        id: 5,
        nome: "Zumbi Mage",
        life: 10,
        attack: 25,
        defense: 5,
        price: 11,
        url:"https://p.kindpng.com/picc/s/108-1087090_dark-wizard-png-plants-vs-zombies-2-zumbi.png",
    },
    {
        id: 6,
        nome: "Orc",
        life: 15,
        attack: 35,
        defense: 10,
        price: 20,
        url:"https://p.kindpng.com/picc/s/729-7297369_orc-png-dungeons-and-dragons-characters-orc-transparent.png",
    },
    {
        id: 7,
        nome: "Zumbi",
        life: 4,
        attack: 5,
        defense: 2,
        price: 1,
        url:"https://p.kindpng.com/picc/s/496-4961523_zombies-zombie-zumbi-morto-mortovivo-zombiegirl-female-zombie.png",
    },
    {
        id: 8,
        nome: "Dwarf",
        life: 50,
        attack: 10,
        defense: 20,
        price: 18,
        url:"https://p.kindpng.com/picc/s/488-4880190_dungeons-and-dragons-dwarf-hd-png-download.png",
    },
    {
        id: 9,
        nome: "Death Knight",
        life: 35,
        attack: 26,
        defense: 14,
        price: 16,
        url:"https://p.kindpng.com/picc/s/458-4583298_dungeons-and-dragons-death-knight-hd-png-download.png",
    },
    {
        id: 10,
        nome: "Elf Arch",
        life: 34,
        attack: 25,
        defense: 6,
        price: 17,
        url:  "https://p.kindpng.com/picc/s/373-3732297_dc-elf-dungeons-and-dragons-tower-of-doom.png",
    },
    {
        id: 11,
        nome: "Cyclops",
        life: 40,
        attack: 36,
        defense: 15,
        price: 26,
        url: "https://p.kindpng.com/picc/s/228-2286983_fairytale-creatures-png-cyclops-dungeons-and-dragons-transparent.png",
    },
    {
        id: 12,
        nome: "Beast",
        life: 38,
        attack: 17,
        defense: 14,
        price: 23,
        url: "https://p.kindpng.com/picc/s/261-2615584_dungeons-dragons-hd-png-download.png",
    },
    {
        id: 13,
        nome: "Troll",
        life: 50,
        attack: 21,
        defense: 5,
        price: 12,
        url: "https://p.kindpng.com/picc/s/294-2942050_5th-edition-dungeons-and-dragons-monsters-hd-png.png",
    },
    {
        id: 14,
        nome: "Crow Archer",
        life: 8,
        attack: 5,
        defense: 1,
        price: 1,
        url: "https://p.kindpng.com/picc/s/588-5885331_dungeons-and-dragons-kenku-hd-png-download.png",
    },
    {
        id: 15,
        nome: "Samurai",
        life: 26,
        attack: 23,
        defense: 16,
        price: 19,
        url:  "https://p.kindpng.com/picc/s/72-727658_dungeons-and-dragons-samurai-hd-png-download.png",
    },
    {
        id: 16,
        nome: "Dragon Warrior",
        life: 42,
        attack: 45,
        defense: 20,
        price: 30,
        url: "https://p.kindpng.com/picc/s/127-1279970_bioshock-infinite-handyman-concept-art-png-download-dragonborn.png",
    },
    {
        id: 17,
        nome: "Demon Dinosaur",
        life: 48,
        attack: 38,
        defense: 22,
        price: 35,
        url: "https://p.kindpng.com/picc/s/181-1812490_transparent-yee-dinosaur-png-demon-lord-dungeons-dragons.png",
    },
    {
        id: 18,
        nome: "Dragon Bard",
        life: 25,
        attack: 5,
        defense: 30,
        price: 20,
        url: "https://p.kindpng.com/picc/s/206-2060754_dnd-5e-dragonborn-bard-hd-png-download.png",
    },
    {
        id: 19,
        nome: "Dragon",
        life: 60,
        attack: 45,
        defense: 30,
        price: 50,
        url: "https://p.kindpng.com/picc/s/206-2060991_vsauce2-on-twitter-final-fantasy-viii-tiamat-hd.png",
    },
    {
        id: 20,
        nome: "Cereberus",
        life: 55,
        attack: 42,
        defense: 32,
        price: 48,
        url:  "https://p.kindpng.com/picc/s/324-3249708_demogorgon-dungeons-and-dragons-hd-png-download.png",
    },
 
    
];